# Generated by Django 4.2.13 on 2024-07-23 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_user_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recipe",
        ),
    ]
